common: &COMMON
  github_app_id: 'asdf'
  github_app_secret: 'asdf'
  bitbucket_app_id: 'asdf'
  bitbucket_app_secret: 'asdf'
  twitter_app_id: 'asdf'
  twitter_app_secret: 'asdf'

test:
  <<: *COMMON

development:
  <<: *COMMON

production:
  <<: *COMMON
